---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sparknotebook-deployment
spec:
  serviceName: sparknotebook
  replicas: 1
  selector:
    matchLabels:
      app: sparknotebook
  template:
    metadata:
      labels:
        app: sparknotebook
    spec:
      securityContext: # as non-root
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: sparknotebook
          image: dunnkers/disease-spread:spark
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8888
          volumeMounts:
            - mountPath: /home/jovyan
              name: jupyter-storage-spark
  volumeClaimTemplates:
  - metadata:
      name: jupyter-storage-spark
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sparknotebook
  name: sparknotebook-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30450
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: sparknotebook
  sessionAffinity: None
  type: LoadBalancer