---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodbnotebook-deployment
spec:
  serviceName: mongodbnotebook
  replicas: 1
  selector:
    matchLabels:
      app: mongodbnotebook
  template:
    metadata:
      labels:
        app: mongodbnotebook
    spec:
      securityContext: # as non-root
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: mongodbnotebook
          image: eu.gcr.io/sixth-utility-268609/mongodb-inserter:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8888
          volumeMounts:
            - mountPath: /home/jovyan
              name: jupyter-storage-mongodb
          env:
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongodb-root-password
                  name: my-mongodb
  volumeClaimTemplates:
  - metadata:
      name: jupyter-storage-mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodbnotebook
  name: mongodbnotebook-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: mongodbnotebook
  sessionAffinity: None
  type: LoadBalancer