apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      my-mongodb'
  creationTimestamp: "2020-03-23T19:42:11Z"
  generateName: my-mongodb-6c6c4dcc7f-
  labels:
    app: mongodb
    chart: mongodb-7.8.7
    pod-template-hash: 6c6c4dcc7f
    release: my-mongodb
  name: my-mongodb-6c6c4dcc7f-lvh5c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: my-mongodb-6c6c4dcc7f
    uid: 29c7e2d6-6064-11ea-8edd-42010aa601b8
  resourceVersion: "8545190"
  selfLink: /api/v1/namespaces/default/pods/my-mongodb-6c6c4dcc7f-lvh5c
  uid: 63ced687-6d3e-11ea-aab6-42010aa60063
spec:
  containers:
  - env:
    - name: MONGODB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-root-password
          name: my-mongodb
    - name: MONGODB_SYSTEM_LOG_VERBOSITY
      value: "0"
    - name: MONGODB_DISABLE_SYSTEM_LOG
      value: "no"
    - name: MONGODB_ENABLE_IPV6
      value: "no"
    - name: MONGODB_ENABLE_DIRECTORY_PER_DB
      value: "no"
    image: docker.io/bitnami/mongodb:4.2.3-debian-10-r31
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - mongo
        - --eval
        - db.adminCommand('ping')
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: my-mongodb
    ports:
    - containerPort: 27017
      name: mongodb
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - mongo
        - --eval
        - db.adminCommand('ping')
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 100m
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/mongodb
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-vwqpd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-cluster-1-larger-pool-d297a696-ww2k
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-mongodb
  - name: default-token-vwqpd
    secret:
      defaultMode: 420
      secretName: default-token-vwqpd
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-23T19:42:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-03-23T19:42:57Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-03-23T19:42:57Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-03-23T19:42:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://395ecbaf33af02648f1bfac7528edc116ea83465a11d317234efea982f27cb8b
    image: bitnami/mongodb:4.2.3-debian-10-r31
    imageID: docker-pullable://bitnami/mongodb@sha256:fc931d8dad56097d2d4d633f2d829b94a246d60652661b90d6e92432351e33f8
    lastState: {}
    name: my-mongodb
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-03-23T19:42:47Z"
  hostIP: 10.166.0.52
  phase: Running
  podIP: 10.0.2.162
  qosClass: Burstable
  startTime: "2020-03-23T19:42:11Z"
