apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-07T11:09:50Z"
  labels:
    app: mongodb
    chart: mongodb-7.8.7
    heritage: Helm
    release: my-mongodb
  name: my-mongodb
  namespace: default
  resourceVersion: "3414424"
  selfLink: /api/v1/namespaces/default/services/my-mongodb
  uid: 29ba9454-6064-11ea-8edd-42010aa601b8
spec:
  clusterIP: 10.4.14.86
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: mongodb
  selector:
    app: mongodb
    release: my-mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
