apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-24T11:01:17Z"
  labels:
    app: mongodb
    chart: mongodb-7.8.10
    heritage: Tiller
    release: my-mongodb
  name: my-mongodb-headless
  namespace: default
  resourceVersion: "8745495"
  selfLink: /api/v1/namespaces/default/services/my-mongodb-headless
  uid: c95a00f8-6dbe-11ea-aab6-42010aa60063
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
    release: my-mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
