---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-spark-zeppelin
spec:
  serviceName: my-spark-zeppelin
  replicas: 1
  selector:
    matchLabels:
      component: my-spark-zeppelin
  template:
    metadata:
      labels:
        chart: spark-1.0.0
        component: my-spark-zeppelin
        heritage: Tiller
        release: my-spark
    spec:
      containers:
      - env:
        - name: SPARK_MASTER
          value: spark://my-spark-master:7077
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
                key: mongodb-root-password
                name: my-mongodb
        image: mcr.microsoft.com/mmlspark/zeppelin:v4_mini
        imagePullPolicy: IfNotPresent
        name: my-spark-zeppelin
        volumeMounts:
          - mountPath: /zeppelin/notebook
            name: zeppelin-storage
        #   - mountPath: /zeppelin/conf
        #     name: zeppelin-conf-storage
        #   - mountPath: /zeppelin/interpreter
        #     name: zeppelin-interpreter-storage
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
  volumeClaimTemplates:
  - metadata:
      name: zeppelin-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi